#!/usr/bin/env bash
# Generate every per-project .env from the single root .env.
#
# Compose reads a .env next to each compose.yml, so a multi-project layout
# normally means several credential files that drift apart. This keeps ONE
# editable file and treats the rest as build output — the generated files carry
# a "DO NOT EDIT" header for exactly that reason.
#
#   cp .env.example .env && chmod 600 .env && $EDITOR .env
#   ./scripts/render-env.sh
#
# Idempotent. Rerun after any change to the root .env.

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${ROOT}/.env"

die() { printf '\033[31mERROR\033[0m %s\n' "$*" >&2; exit 1; }
ok()  { printf '\033[32mok\033[0m    %s\n' "$*"; }
warn(){ printf '\033[33mwarn\033[0m  %s\n' "$*"; }

[[ -f "$SRC" ]] || die "$SRC not found. Start with: cp .env.example .env"

# Refuse to run with a world-readable secrets file rather than propagating the
# problem into four more files.
perms="$(stat -c '%a' "$SRC")"
[[ "$perms" == "600" ]] || die ".env is mode ${perms}; must be 600. Run: chmod 600 $SRC"

set -a
# shellcheck source=/dev/null  # path is runtime-determined by design
. "$SRC"
set +a

# Fail loudly on anything unset. A blank password does not error at deploy
# time — it produces a service with no password, which is worse.
REQUIRED=(DOMAIN HOSTNAME ADMIN_USER DATA_ROOT ACME_EMAIL GRAFANA_ADMIN_PASSWORD
          ALERT_SENDER ALERT_RECIPIENT BACKUP_PASSPHRASE)
missing=()
for v in "${REQUIRED[@]}"; do [[ -n "${!v:-}" ]] || missing+=("$v"); done
[[ ${#missing[@]} -eq 0 ]] || die "unset in .env: ${missing[*]}"

[[ -n "${CLOUDFLARE_API_TOKEN:-}" ]] || warn "CLOUDFLARE_API_TOKEN unset — TLS issuance will fail"
if [[ "${OFFSITE_ENABLED:-false}" == "true" && -z "${OFFSITE_ACCESS_KEY:-}" ]]; then
  warn "OFFSITE_ENABLED=true but OFFSITE_ACCESS_KEY is unset — off-site backup will fail"
fi

HDR="# GENERATED by scripts/render-env.sh — DO NOT EDIT.
# Edit the root .env and rerun. Changes here are overwritten without warning."

write_env() {
  local dest="$1"; shift
  mkdir -p "$(dirname "$dest")"
  { printf '%s\n\n' "$HDR"; printf '%s\n' "$@"; } > "$dest"
  chmod 600 "$dest"
  ok "$(realpath --relative-to="$ROOT" "$dest")"
}

write_env "${ROOT}/monitoring/.env" \
  "GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}" \
  "GF_SERVER_ROOT_URL=https://${DOMAIN}/monitoring/" \
  "PROMETHEUS_RETENTION_TIME=${PROMETHEUS_RETENTION_TIME:-15d}" \
  "PROMETHEUS_RETENTION_SIZE=${PROMETHEUS_RETENTION_SIZE:-4GB}" \
  "BREVO_SMTP_HOST=${BREVO_SMTP_HOST:-}" \
  "BREVO_SMTP_PORT=${BREVO_SMTP_PORT:-587}" \
  "BREVO_SMTP_LOGIN=${BREVO_SMTP_LOGIN:-}" \
  "BREVO_API_KEY=${BREVO_API_KEY:-}" \
  "ALERT_SENDER=${ALERT_SENDER}" \
  "ALERT_RECIPIENT=${ALERT_RECIPIENT}" \
  "TZ=${TZ:-UTC}"

write_env "${ROOT}/proxy-nginx/.env" \
  "DOMAIN=${DOMAIN}" \
  "TAILSCALE_IP=${TAILSCALE_IP:-}" \
  "TZ=${TZ:-UTC}"

write_env "${ROOT}/alert-bridge/.env" \
  "BREVO_API_KEY=${BREVO_API_KEY:-}" \
  "ALERT_SENDER=${ALERT_SENDER}" \
  "ALERT_RECIPIENT=${ALERT_RECIPIENT}" \
  "GRAFANA_URL=https://${DOMAIN}/monitoring/" \
  "HOSTNAME=${HOSTNAME}"

write_env "${ROOT}/.backup-env" \
  "BACKUP_PASSPHRASE=${BACKUP_PASSPHRASE}" \
  "BACKUP_KEEP_DAILY=${BACKUP_KEEP_DAILY:-14}" \
  "BACKUP_KEEP_WEEKLY=${BACKUP_KEEP_WEEKLY:-8}" \
  "OFFSITE_ENABLED=${OFFSITE_ENABLED:-false}" \
  "OFFSITE_BUCKET=${OFFSITE_BUCKET:-}" \
  "OFFSITE_BUDGET_BYTES=${OFFSITE_BUDGET_BYTES:-9900000000}" \
  "OFFSITE_KEEP=${OFFSITE_KEEP:-30}"

# Written outside the repo: rclone and certbot read from /etc, and these hold
# live credentials that must not sit in a working tree at all.
if [[ "${OFFSITE_ENABLED:-false}" == "true" && $EUID -eq 0 ]]; then
  mkdir -p /etc/rclone
  cat > /etc/rclone/rclone.conf <<RCLONE
[offsite]
type = s3
provider = Other
env_auth = false
access_key_id = ${OFFSITE_ACCESS_KEY}
secret_access_key = ${OFFSITE_SECRET_KEY}
region = ${OFFSITE_REGION}
endpoint = ${OFFSITE_ENDPOINT}
acl = private
RCLONE
  chmod 600 /etc/rclone/rclone.conf
  ok "/etc/rclone/rclone.conf"
fi

if [[ -n "${CLOUDFLARE_API_TOKEN:-}" && $EUID -eq 0 ]]; then
  mkdir -p /etc/letsencrypt
  printf 'dns_cloudflare_api_token = %s\n' "$CLOUDFLARE_API_TOKEN" > /etc/letsencrypt/cloudflare.ini
  chmod 600 /etc/letsencrypt/cloudflare.ini
  ok "/etc/letsencrypt/cloudflare.ini"
elif [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  warn "not root — skipped /etc/letsencrypt/cloudflare.ini (rerun with sudo)"
fi

printf '\nDone. Generated files are mode 600 and gitignored.\n'
